(require 'server)
(unless (server-running-p)
  (server-start))

(add-to-list 'load-path "~/.emacs.d/lisp")
(load-library "visual")
(load-library "general")
(load-library "system")
(load-library "package-specific")
;; (load-library "org")
;; (load-library "dev-web")
;; (load-library "functions")
;; (load-library "dev-cpp")
;; (load-library "dev-csharp")
;; (load-library "dev-lisp")
