(add-to-list 'auto-mode-alist '("\\.exs?$" . elixir-mode))
(add-hook 'elixir-mode-hook
          (lambda () (add-hook 'before-save-hook 'elixir-format nil t)))
(require 'alchemist)
(setq alchemist-key-command-prefix (kbd "C-c a"))
(setq alchemist-hooks-test-on-save nil)
(setq alchemist-hooks-compile-on-save t)
(add-to-list 'purpose-user-mode-purposes '(elixir-mode . elixir))
(add-to-list 'purpose-user-name-purposes '("*alchemist test report*" . elixir-test))
(add-to-list 'purpose-user-name-purposes '("*alchemist mix*" . elixir-mix))
(purpose-compile-user-configuration)
